modLoader = "kotlinforforge"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "interstellar"
version = "${version}"
displayName = "Interstellar"
authors = "RedstoneWizard08, Nionics, Bogdanasaurus, Stardust Modding Contributors"
description = "Explore the universe in style."
#logoFile = ""

[[dependencies.interstellar]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.interstellar]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.interstellar]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.interstellar]]
modId = "kotlinforforge"
mandatory = true
versionRange = "[${kotlin_for_forge_version}]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.interstellar]]
modId = "cloth_config"
mandatory = true
versionRange = "[${kotlin_for_forge_version}]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.interstellar]]
modId = "badpackets"
mandatory = true
versionRange = "[0.4,)"
ordering = "NONE"
side = "BOTH"
