modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "interstellar"
version = "${version}"
displayName = "Create: Interstellar"
authors = "Nionics, RedstoneWizard08"
description = '''
Explore the universe in style.
'''
#logoFile = ""

[[dependencies.interstellar]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.interstellar]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.interstellar]]
modId = "architectury"
mandatory = true
versionRange = "[6.5.77,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.interstellar]]
modId = "cloth-config"
mandatory = true
versionRange = "[8.3.103,)"
ordering = "AFTER"
side = "BOTH"
